runtime: python313
entrypoint: gunicorn -b :$PORT run:app

env_variables:
  DATABASE_URL: ""
  DB_PATH: /tmp/rps.db
  EVENTS_DIR: gs://directed-sonar-rps-data/events
  MODELS_DIR: gs://directed-sonar-rps-data/models
  EXPORTS_DIR: gs://directed-sonar-rps-data/exports
  TRAINING_EXECUTION_MODE: task_queue
  TASKS_PROJECT_ID: directed-sonar-429119-u2
  TASKS_LOCATION: us-west3
  TASKS_QUEUE: rps-training
  TRAINING_WORKER_URL: https://directed-sonar-429119-u2.uw.r.appspot.com
  INTERNAL_WORKER_TOKEN: N43GdTyvV9UYubWrNtav_1i7Jtg77x0Ym4Mus7AzCfTaQKZl10ZFemFM1joCufCH

service_account: circa-orbit-sa@directed-sonar-429119-u2.iam.gserviceaccount.com
